#!/usr/bin/env python3
r"""Flatten the manuscript into single self-contained .tex files for journal submission.

Produces (in MANUSCRIPT/):
  manuscript.tex    -- main.tex with every \input expanded inline and the bibliography
                       embedded from main.bbl (compiles standalone: pdflatex twice, no bibtex).
  supplementary.tex -- supplement.tex with every \input (the S-tables) expanded inline.

Figures are NOT inlined (they are binary PDFs); \graphicspath is rewritten so the output
files compile from MANUSCRIPT/ against ../figures/main/. Run after paper/latex/build.sh
(needs the fragments in generated/, the tables in tables/out/, and main.bbl).

Usage:  python paper/latex/make_submission.py
"""
from __future__ import annotations

import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))            # paper/latex
ROOT = os.path.dirname(os.path.dirname(HERE))                # repo root
OUT = os.path.join(ROOT, "MANUSCRIPT")

INPUT_RE = re.compile(r"\\input\{([^}]*)\}")


def expand(path: str, seen: tuple = ()) -> str:
    r"""Return the file's text with every \input recursively inlined.

    LaTeX resolves \input paths against the COMPILE directory (paper/latex/),
    not against the directory of the file that contains the \input, so nested
    inputs (e.g. generated/results.tex -> floats/F1_design.tex ->
    ../../tables/out/T1_panel.tex) must resolve from HERE."""
    if path in seen:
        raise SystemExit(f"cyclic \\input at {path}")
    with open(path, encoding="utf-8") as f:
        text = f.read()

    def repl(m: re.Match) -> str:
        target = m.group(1)
        if not os.path.splitext(target)[1]:
            target += ".tex"
        child = os.path.normpath(os.path.join(HERE, target))
        inner = expand(child, seen + (path,))
        return (f"% >>> inlined from {os.path.relpath(child, ROOT).replace(os.sep, '/')}\n"
                f"{inner}\n"
                f"% <<< end inline\n")

    return INPUT_RE.sub(repl, text)


def fix_graphicspath(text: str) -> str:
    # output lives in MANUSCRIPT/, figures in repo/figures/main -> ../figures/main/
    return text.replace("{{../../figures/main/}}", "{{../figures/main/}}")


def build_manuscript() -> None:
    text = expand(os.path.join(HERE, "main.tex"))
    text = fix_graphicspath(text)
    # embed the bibliography: drop \bibliographystyle + \bibliography, inline main.bbl
    with open(os.path.join(HERE, "main.bbl"), encoding="utf-8") as f:
        bbl = f.read()
    text = re.sub(r"\\bibliographystyle\{[^}]*\}\s*", "", text)
    embedded = "% >>> bibliography embedded from main.bbl\n" + bbl + "\n% <<< end bibliography"
    text = re.sub(r"\\bibliography\{[^}]*\}", lambda _m: embedded, text)
    header = ("% SINGLE-FILE MANUSCRIPT for submission. Auto-generated by\n"
              "% paper/latex/make_submission.py -- DO NOT hand-edit; edit paper/sections/*.md\n"
              "% and rerun build.sh + make_submission.py. Compile: pdflatex twice (no bibtex).\n")
    write(os.path.join(OUT, "manuscript.tex"), header + text)


def build_supplement() -> None:
    text = expand(os.path.join(HERE, "supplement.tex"))
    text = fix_graphicspath(text)
    header = ("% SINGLE-FILE SUPPLEMENT for submission. Auto-generated by\n"
              "% paper/latex/make_submission.py -- DO NOT hand-edit. Compile: pdflatex twice.\n")
    write(os.path.join(OUT, "supplementary.tex"), header + text)


def write(dst: str, text: str) -> None:
    with open(dst, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    n_input = len(INPUT_RE.findall(text))
    assert n_input == 0, f"{dst}: {n_input} \\input left unexpanded"
    print(f"wrote {os.path.relpath(dst, ROOT).replace(os.sep, '/')}  "
          f"({len(text.splitlines())} lines, 0 external \\input)")


if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    build_manuscript()
    build_supplement()
    print("Single-file submission sources ready in MANUSCRIPT/.")
